### PR TITLE
Add blackbelt

### PR DESCRIPTION
**Pull request by kylef**
This creates a single-command installation for black-belt providing you have homebrew installed (which every macOS user probably does these days).

```shell
$ brew install apiaryio/formulae/blackbelt
```

I am not entirely sure if it is worth having a homebrew formula but wanted to create the PR for discussion. There is both upsides and downsides so we should evaluate if it makes sense.

#### Upsides

- Consumer of black-belt doesn't need to know about implementation details (is it on Python, RubyGems, NPM etc)
- Significantly simplifies installation of black-belt. There isn't really a simple way to install black-belt the right way (without sudo, easy_install) unless you know Python well. Shouldn't run easy_install as it doesn't use SSL or validate what is installed (offer upgrade or uninstallation), and especially since it is often ran as root via sudo...
- All dependency versions are locked and controlled to produce further reliably installations.
- Possibly makes the upgrade path easier for users.

#### Downsides

- Complicates release process slightly. Using [poet](https://github.com/tdsmith/homebrew-pypi-poet) I was able to generate the entire formula.

/c @Almad @honzajavorek @abtris for feedback

### CODE REVIEW

**Comment by kylef** [comment]
The Formula can be generated using the following command after installing poet:

NOTE: Should be ran in a Virtualenv with blackbelt installed.

```shell
$ poet -f blackbelt | sed 's/Shiny new formula/Internal toolbelt on steroids/' > /usr/local/Homebrew/Library/Taps/apiaryio/homebrew-formulae/Formula/blackbelt.rb
```

**Review by abtris — APPROVED** [review]
👍

**Comment by abtris** [comment]
I think this is good idea. I can make similar formula for incident-report.

**Comment by honzajavorek** [comment]
Can we generate it in black belt's CI after publishing a new version to PyPI?

**Comment by kylef** [comment]
> Can we generate it in black belt's CI after publishing a new version to PyPI?

~Let me give that a go.~ The release process isn't done on CI and uses something I'm unfamiliar with so I won't be able to do this easily.

**Comment by abtris** [comment]
Yes, but we can add release there. Semantic release is one of issue too.

**Pull request merged**
